### ISSUE TITLE
Absolute Paths

### ISSUE THREAD

**Issue by allella** [SpaceCowboy326/open_data_gvl#10]
@SpaceCowboy326 I'm probably going to run this in a sub-directory of data.openupstate.org and the hard coded src="/..." on the generated header tags is not going to work.

How would I change that to ./ ?

```
<link href=/css/app.9eb7f534.css rel=preload as=style>
<link href=/js/app.cde81c9f.js rel=preload as=script>
<link href=/js/chunk-vendors.c1adc249.js rel=preload as=script><link href=/css/app.9eb7f534.css rel=stylesheet>
```

Thanks

**Comment by SpaceCowboy326** [comment]
@allella it looks like you should be able to configure that via a vue.js config file, described here:
https://cli.vuejs.org/config/#publicpath

So it sounds like if you create a vue.js.config file in the main directory for the app with the content:
`module.exports = {
    publicPath: "./"
}`

Then `rerun npm run build`, the references should be updated.

**Comment by allella** [comment]
Thanks. I was able to get the paths right using a vue.config.js in the same directory as the packages.json with the content

```
module.exports = {
    publicPath: '/path-to-the/subdirectory/'
}

```
